name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  builds:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm install
      - run: npm test
        env:
            AUTH_HASH: ${{ secrets.AUTH_HASH }}
            AUTH_KEY: ${{ secrets.AUTH_KEY }}
            AUTH_MAX_AGE: ${{ secrets.AUTH_MAX_AGE }}
            DB_DB: ${{ secrets.DB_DB }}
            DB_HOST: ${{ secrets.DB_HOST }}
            DB_PASS: ${{ secrets.DB_PASS }}
            DB_PORT: ${{ secrets.DB_PORT }}
            DB_USER: ${{ secrets.DB_USER }}
            LIMITER_DELAY: ${{ secrets.LIMITER_DELAY }}
            LIMITER_MAX: ${{ secrets.LIMITER_MAX }}
            LIMITER_RETRY: ${{ secrets.LIMITER_RETRY }}
            SERVER_PORT: ${{ secrets.SERVER_PORT }}
      - run: npm run build
      - uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          port: ${{ secrets.DEPLOY_PORT }}
          key: ${{ secrets.DEPLOY_KEY }}
          source: "dist/wkblog.js"
          target: "${{ secrets.DEPLOY_TARGET }}"
        